version: '3.8'
services:
  api:
    container_name: api
    restart: always
    build: .
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes: 
 data: {}
